=== nesl/esp/xml/espml.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="system">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="id" type="xs:anyURI"/>
                <xs:element name="field" minOccurs="1" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element ref="id"></xs:element>
                            <xs:element ref="location"></xs:element>
                            <xs:element ref="description"></xs:element>
                            <xs:element ref="function" minOccurs="0" maxOccurs="unbounded"></xs:element>
                            <xs:element name="platform" minOccurs="1" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element ref="id"></xs:element>
                                        <xs:element ref="location"></xs:element>
                                        <xs:element ref="description"></xs:element>
                                        <xs:element ref="function" minOccurs="0"
                                            maxOccurs="unbounded"/>
                                        <xs:element name="sensor" minOccurs="0" maxOccurs="unbounded">
                                            <xs:complexType>
                                                <xs:sequence>
                                                  <xs:element ref="id"></xs:element>
                                                  <xs:element ref="location"></xs:element>
                                                  <xs:element ref="description"/>
                                                  <xs:element ref="function" minOccurs="0" maxOccurs="unbounded"/>
                                                  <xs:element name="type" type="xs:string"/>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <!-- Simple element definitions -->
    <xs:element name="id" type="xs:integer"/>
    <xs:element name="description" type="xs:string"/>

    <!-- Complex element definitions -->
    <xs:element name="function">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="description" type="xs:string"></xs:element>
                <xs:element name="parameter" minOccurs="0" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="description" type="xs:string"></xs:element>
                            <xs:element name="value" minOccurs="0" maxOccurs="1" type="xs:string"></xs:element>
                        </xs:sequence>
                        <xs:attribute name="name" type="xs:string"/>
                    </xs:complexType>
                </xs:element>
                <xs:element name="output" minOccurs="0" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="URI" minOccurs="1" maxOccurs="1" type="xs:anyURI"></xs:element>
                        </xs:sequence>
                        <xs:attribute name="type" type="xs:string"/>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
            <xs:attribute name="name" type="xs:string"/>
        </xs:complexType>
    </xs:element>

    <xs:element name="location">
        <xs:annotation>
            <xs:documentation>Point: Specify three values representing x,y,z coordintes.</xs:documentation>
            <xs:documentation>Polygon:  Must be four pairs of x,y,z coordinates with last being identical to the first..</xs:documentation>
        </xs:annotation>
        <xs:complexType>
            <xs:sequence>
                <xs:element name="Mobile" minOccurs="0" maxOccurs="1"></xs:element>
                <xs:choice>
                    <xs:element name="point" minOccurs="1" maxOccurs="unbounded">
                        <xs:complexType>
                            <xs:sequence>
                                <xs:element name="pos" type="xs:string"/>
                            </xs:sequence>
                        </xs:complexType>
                    </xs:element>
                    <xs:element name="polygon" minOccurs="1" maxOccurs="unbounded">
                        <xs:complexType>
                            <xs:sequence>
                                <xs:element name="poslist" type="xs:string"/>
                            </xs:sequence>
                        </xs:complexType>
                    </xs:element>
                </xs:choice>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="query">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="system" minOccurs="1" maxOccurs="unbounded"></xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    
    <xs:element name="mediator">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="id" type="xs:anyURI"/>
                <xs:element ref="location"></xs:element>
                <xs:element ref="description"></xs:element>
                <xs:element name="system" minOccurs="0" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="id" type="xs:anyURI"/>
                            <xs:element ref="description"></xs:element>
                        </xs:sequence>
                    </xs:complexType>
                    </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== nesl/esp/xml/mediator1.xml
<?xml version="1.0" encoding="UTF-8"?>
<mediator xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="espml.xsd">
 <id>http://128.97.93.154:9081</id>
 <location>
  <polygon>
   <poslist>34.0888,-118.4305,0.00</poslist>
  </polygon>
 </location>
 <description>Mediator for the UCLA region.</description>
 <system>
  <id>http://128.97.93.154:7081</id>
  <description>SoundScape</description>
 </system>
 <system>
  <id>http://128.97.93.154:7082</id>
  <description>SensorBase</description>
 </system>
 <system>
  <id>http://128.97.93.154:7083</id>
  <description>Weather Stations</description>
 </system>
 <system>
  <id>http://128.97.93.154:7084</id>
  <description>SOS PhotoDiode</description>
 </system>
 <system>
  <id>http://128.97.93.154:7086</id>
  <description>SonyCam</description>
 </system>
 <system>
  <id>http://128.97.93.154:7087</id>
  <description>iTunes</description>
 </system>
 <system>
  <id>http://128.97.93.154:7088</id>
  <description>Beach Cams</description>
 </system>
</mediator>
