=== nesl/esp/xml/espml.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="system">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="id" type="xs:anyURI"/>
                <xs:element name="field" minOccurs="1" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element ref="id"></xs:element>
                            <xs:element ref="location"></xs:element>
                            <xs:element ref="description"></xs:element>
                            <xs:element ref="function" minOccurs="0" maxOccurs="unbounded"></xs:element>
                            <xs:element name="platform" minOccurs="1" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element ref="id"></xs:element>
                                        <xs:element ref="location"></xs:element>
                                        <xs:element ref="description"></xs:element>
                                        <xs:element ref="function" minOccurs="0"
                                            maxOccurs="unbounded"/>
                                        <xs:element name="sensor" minOccurs="0" maxOccurs="unbounded">
                                            <xs:complexType>
                                                <xs:sequence>
                                                  <xs:element ref="id"></xs:element>
                                                  <xs:element ref="location"></xs:element>
                                                  <xs:element ref="description"/>
                                                  <xs:element ref="function" minOccurs="0" maxOccurs="unbounded"/>
                                                  <xs:element name="type" type="xs:string"/>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <!-- Simple element definitions -->
    <xs:element name="id" type="xs:integer"/>
    <xs:element name="description" type="xs:string"/>

    <!-- Complex element definitions -->
    <xs:element name="function">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="description" type="xs:string"></xs:element>
                <xs:element name="parameter" minOccurs="0" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="description" type="xs:string"></xs:element>
                            <xs:element name="value" minOccurs="0" maxOccurs="1" type="xs:string"></xs:element>
                        </xs:sequence>
                        <xs:attribute name="name" type="xs:string"/>
                    </xs:complexType>
                </xs:element>
                <xs:element name="output" minOccurs="0" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="URI" minOccurs="1" maxOccurs="1" type="xs:anyURI"></xs:element>
                        </xs:sequence>
                        <xs:attribute name="type" type="xs:string"/>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
            <xs:attribute name="name" type="xs:string"/>
        </xs:complexType>
    </xs:element>

    <xs:element name="location">
        <xs:annotation>
            <xs:documentation>Point: Specify three values representing x,y,z coordintes.</xs:documentation>
            <xs:documentation>Polygon:  Must be four pairs of x,y,z coordinates with last being identical to the first..</xs:documentation>
        </xs:annotation>
        <xs:complexType>
            <xs:sequence>
                <xs:element name="Mobile" minOccurs="0" maxOccurs="1"></xs:element>
                <xs:choice>
                    <xs:element name="point" minOccurs="1" maxOccurs="unbounded">
                        <xs:complexType>
                            <xs:sequence>
                                <xs:element name="pos" type="xs:string"/>
                            </xs:sequence>
                        </xs:complexType>
                    </xs:element>
                    <xs:element name="polygon" minOccurs="1" maxOccurs="unbounded">
                        <xs:complexType>
                            <xs:sequence>
                                <xs:element name="poslist" type="xs:string"/>
                            </xs:sequence>
                        </xs:complexType>
                    </xs:element>
                </xs:choice>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="query">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="system" minOccurs="1" maxOccurs="unbounded"></xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    
    <xs:element name="mediator">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="id" type="xs:anyURI"/>
                <xs:element ref="location"></xs:element>
                <xs:element ref="description"></xs:element>
                <xs:element name="system" minOccurs="0" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="id" type="xs:anyURI"/>
                            <xs:element ref="description"></xs:element>
                        </xs:sequence>
                    </xs:complexType>
                    </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== nesl/esp/system/sensorbase/sensorbase_function.xml
<?xml version="1.0" encoding="UTF-8"?>
<system xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="../../xml/espml.xsd">
 <id>http://128.97.93.154:7082</id>
 <field>
  <id>1</id>
  <location>
   <polygon>
    <poslist>34.0888,-118.4305,0.00</poslist>
   </polygon>
  </location>
  <description>Upload and query system for Soundscape server.</description>
  <function name="createProject">
  </function>
  <function name="publishData">
  </function>
  <function name="performQuery">
  </function>
 </field>
</system>

=== nesl/esp/system/soundscape/soundscape_system.xml
<?xml version="1.0" encoding="UTF-8"?>
<system xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="../../xml/espml.xsd">
 <id>http://128.97.93.154:7081</id>
 <field>
  <id>1</id>
  <location>
   <point>
    <pos>34.0888,-118.4305,0.00</pos>
   </point>
  </location>
  <description>Upload and query system for Soundscape server.</description>
  <function name="getSessionId">
  <description>Returns a unique session id.</description>
  </function>
  <function name="uploadLocation">
    <description>Upload a location for a session id.</description>
    <parameter name="sessionId">
      <description>Identifies the session to which the timestamp
      should be added.</description>
    </parameter>
    <parameter name="timestamp">
      <description>Represents the time when the location was recorded.</description>
    </parameter>
    <parameter name="location">
      <description>Location string of the format "latitude,longitude,altitude"</description>
    </parameter>
  </function>
  <function name="uploadMedia">
    <description></description>
    <parameter name="sessionId">
      <description>Identifies the session to which the timestamp
      should be added.</description>
    </parameter>
    <parameter name="timestamp">
      <description>Represents the time when the location was recorded.</description>
    </parameter>
    <parameter name="mediaFile">
      <description>Base64 encoded mediafile data.</description>
    </parameter>
  </function>
 </field>
</system>

=== nesl/esp/system/sensorbase/sensorbase_system.xml
<?xml version="1.0" encoding="UTF-8"?>
<system xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="../../xml/espml.xsd">
 <id>http://128.97.93.154:7082</id>
 <field>
  <id>1</id>
  <location>
   <point>
    <pos>34.0888,-118.4305,0.00</pos>
   </point>
  </location>
  <description>Upload and query system for Sensorbase system.</description>
  <function name="createProject">
    <description>Upload a location for a session id.</description>
    <parameter name="projectName">
      <description>The name of the actual project which is used during search requests.</description>
    </parameter>
    <parameter name="projectDescription">
      <description>Description for the project itself.</description>
    </parameter>
    <parameter name="uspsAddress">
      <description>USPS address for the information for data that you are logging.</description>
    </parameter>
    <parameter name="nwCoordinate">
      <description>The north and west bound coordinate in "Lat,Long" format.</description>
    </parameter>
    <parameter name="seCoordinate">
      <description>The south and east bound coordinate in "Lat,Long" format.</description>
    </parameter>
    <parameter name="minmaxAltitude">
      <description>The minimum and maximum MSL altitude in meters in "Min,Max" format.</description>
    </parameter>
    <parameter name="dataReadUser">
      <description>Data read permission for any users in "allow" or "deny" format.</description>
    </parameter>
    <parameter name="dataWriteUser">
      <description>Data write permission for any users in "allow" or "deny" format.</description>
    </parameter>
    <parameter name="dataReadGroup">
      <description>Data read permission for all users of a group in "allow" or "deny" format.</description>
    </parameter>
    <parameter name="dataWriteGroup">
      <description>Data read permission for all users of a group in "allow" or "deny" format.</description>
    </parameter>
  </function>
  <function name="publishData">
    <description></description>
    <parameter name="emailAddress">
      <description>The email address of the user.</description>
    </parameter>
    <parameter name="password">
      <description>The password of the user that is publishing.</description>
    </parameter>
    <parameter name="overwriteData">
      <description>Specifies whether to overwrite the existing data with the primary key in "1" or "0" format.</description>
    </parameter>
    <parameter name="dataType">
      <description>The type of data that is being updated, this could be "xml", "text", or "binary".</description>
    </parameter>
    <parameter name="dataFile">
      <description>The actual data that should be published.  In most cases, it will just be a string representing sensorbase xml</description>
    </parameter>
  </function>
  <function name="performQuery">
    <description></description>
    <parameter name="dataType">
      <description>Specifies how the data should be returned which can be "html", "xml" or "text".</description>
    </parameter>
    <parameter name="queryString">
      <description>The actual query to perform.</description>
    </parameter>
  </function>
 </field>
</system>

=== nesl/esp/xml/system2.xml
<?xml version="1.0" encoding="UTF-8"?>
<system xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="espml.xsd">
 <id>http://www.schmidi.com</id>
 <field>
  <id>1</id>
  <location>
   <point>
    <pos>36.2,24.2,0.0</pos>
   </point>
  </location>
  <description>This is the first test field</description>
  <function name="add">
   <parameter name="firstVal">
    <value>1</value>
   </parameter>
   <parameter name="secondVal">
    <value>2</value>
   </parameter> 
  </function>
  <platform>
   <id>1</id>
   <location>
    <point>
     <pos>36.3,24.3,0.0</pos>
    </point>
   </location>
   <description>Test Platform MicaSchmidi</description>
   <function name="sub">
    <parameter name="firstVal">
     <value>1</value>
    </parameter>    
   </function>
   <function name="min">
    <parameter name="firstVal">
     <value>1</value>
    </parameter>   
   </function>
   <sensor>
    <id>1</id>
    <location>
     <point>
      <pos>36.3,24.3,0.0</pos>
     </point>
    </location>
    <description>Put link to datasheet here.</description>
    <function name="mean"/>    
    <type>Temperature</type>
   </sensor>
  </platform>
 </field>
</system>

=== nesl/esp/system/soundscape/soundscape_function2.xml
<?xml version="1.0" encoding="UTF-8"?>
<system xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="../../xml/espml.xsd">
 <id>http://128.97.93.154:7081</id>
 <field>
  <id>1</id>
  <location>
   <polygon>
    <poslist>34.0888,-118.4305,0.00</poslist>
   </polygon>
  </location>
  <function name="uploadLocation">
  </function>
  <function name="uploadMedia">
  </function>
 </field>
</system>

=== nesl/esp/system/sos/sos_function.xml
<?xml version="1.0" encoding="UTF-8"?>
<system xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="../../xml/espml.xsd">
 <id>http://128.97.93.154</id>
 <field>
  <id>1</id>
  <location>
   <polygon>
    <poslist>34.0815,-118.46,0.00 34.0518,-118.46,0.00 34.0509,-118.42,0.00 34.0805,-118.42,0.00 34.0815,-
18.46,0.00</poslist>
   </polygon>
  </location>
  <description>This is a small test field of SOS nodes.</description>
  <function name="getCurrent">
  <description>Returns the current values for all platforms in this field.</description>
  </function>
  <function name="average">
   <description>Returns the average over all platforms in this field.
   </description>
  </function>
  <platform>
   <id>1</id>
   <location>
    <point>
     <pos>34.0689,-118.44,0.00</pos>
    </point>
   </location>
   <description>MicaZ Basestation connected to the gateway.</description>
  </platform>

  <platform>
   <id>182</id>
   <location>
    <point>
     <pos>34.0689,-118.44,0.00</pos>
    </point>
   </location>
   <description>MicaZ node with Mica Sensor Board.</description>
   <sensor>
    <id>1</id>
    <location>
     <point>
      <pos>34.0689,-118.44,0.00</pos>
     </point>
    </location>
    <description>PhotoSensor</description>
    <function name="getCurrentValue">
     <description>Get's the current value for this sensor.
     </description>
    </function>
    <function name="getAverageValue">
      <description>Gets the average for this sensor.
      </description>
      <parameter name="numberElements">
        <description>The number of elements for which the average should be calculated.
	       </description>
      </parameter>
    </function>
    <function name="setSampleInterval">
      <description>Sets the sampling frequency for this sensor.
      </description>
      <parameter name="frequency">
        <description>The frequency at which the sensor should sample.
	</description>
      </parameter>
    </function>
    <type>Light</type>
   </sensor>
  </platform>

  <platform>
   <id>196</id>
   <location>
    <point>
     <pos>34.0682,-118.44,0.00</pos>
    </point>
   </location>
   <description>MicaZ node with Mica Sensor Board.</description>
   <sensor>
    <id>1</id>
    <location>
     <point>
      <pos>34.0682,-118.44,0.00</pos>
     </point>
    </location>
    <description>PhotoSensor</description>
    <function name="getCurrentValue">
     <description>Get's the current value for this sensor.
     </description>
    </function>
    <function name="getAverageValue">
      <description>Gets the average for this sensor.
      </description>
      <parameter name="numberElements">
        <description>The number of elements for which the average should be calculated.
	       </description>
      </parameter>
    </function>
    <function name="setSampleInterval">
      <description>Sets the sampling frequency for this sensor.
      </description>
      <parameter name="frequency">
        <description>The frequency at which the sensor should sample.
   	    </description>
      </parameter>
    </function>
    <type>Light</type>
   </sensor>
  </platform>

 </field>
</system>

=== nesl/esp/web/baseFunctionCall.xml
<?xml version="1.0" encoding="UTF-8"?>
<system xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="../../class/cs219/esp/trunk/xml/espml.xsd">
    <id></id>
    <field>
        <id></id>
        <location>
            <point>
                <pos></pos>
            </point>
        </location>
        <description></description>
        <platform>
            <id></id>
            <location>
                <point>
                    <pos></pos>
                </point>
            </location>
            <description></description>
            <sensor>
                <id></id>
                <location>
                    <point>
                        <pos></pos>
                    </point>
                </location>
                <description></description>
                <type></type>
            </sensor>
        </platform>
    </field>
</system>

=== nesl/esp/xml/query_response.xml
<?xml version="1.0" encoding="UTF-8"?>
<query xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="espml.xsd">

 <system>
 <id>http://www.schmidi.com</id>
   <field>
    <id>1</id>
    <location>
        <polygon>
            <poslist>36.2,24.2,0.0 36.2,24.2,0.0</poslist>
        </polygon>
    </location>
    <description>This is the first test field</description>
    <function name="add">
        <description>This is the first test field</description>
        <parameter name="firstVal">
            <description>This is the first test field</description>
            <value>1</value>
        </parameter>
        <parameter name="secondVal">
            <description>This is the first test field</description>
            <value>2</value>
        </parameter>
    </function>
    <platform>
        <id>1</id>
        <location>
            <point>
                <pos>36.3,24.3,0.0</pos>
            </point>
        </location>
        <description>Test Platform MicaSchmidi</description>
        <function name="sub">
            <description>This is the first test field</description>
            <parameter name="firstVal">
                <description>This is the first test field</description>
                <value>1</value>
            </parameter>
        </function>
        <function name="min">
            <description>This is the first test field</description>
            <parameter name="firstVal">
                <description>This is the first test field</description>
                <value>1</value>
            </parameter>
        </function>
        <sensor>
            <id>1</id>
            <location>
                <point>
                    <pos>36.3,24.3,0.0</pos>
                </point>
            </location>
            <description>Put link to datasheet here.</description>
            <function name="mean">
                <description>This is the first test field</description>
            </function>
            <type>Temperature</type>
        </sensor>
    </platform>
</field>
</system>

 <system>
 <id>http://www.sasank.com</id>
   <field>
    <id>1</id>
    <location>
        <point>
            <pos>36.2,24.2,0.0</pos>
        </point>
    </location>
    <description>This is a small test field of SOS nodes.</description>
    <function name="getCurrent">
        <description>This is the first test field</description>
    </function>
    <function name="average">
        <description>This is the first test field</description>
    </function>
    <platform>
        <id>1</id>
        <location>
            <point>
                <pos>36.3,24.3,0.0</pos>
            </point>
        </location>
        <description>MicaZ Basestation connected to the gateway.</description>
    </platform>
    <platform>
        <id>185</id>
        <location>
            <point>
                <pos>36.304,24.304,2.0</pos>
            </point>
        </location>
        <description>MicaZ node with Mica Sensor Board.</description>
        <sensor>
            <id>1</id>
            <location>
                <point>
                    <pos>36.304,24.304,2.0</pos>
                </point>
            </location>
            <description>PhotoSensor</description>
            <function name="getCurrentValue">
                <description>This is the first test field</description>
            </function>
            <function name="getAverageValue">
                <description>This is the first test field</description>
                <parameter name="numberElements">
                    <description>This is the first test field</description>
                    <value>1</value>
                </parameter>
            </function>
            <function name="setSampleInterval">
                <description>This is the first test field</description>
                <parameter name="frequency">
                    <description>This is the first test field</description>
                    <value>1</value>
                </parameter>
            </function>
            <type>Light</type>
        </sensor>
    </platform>
    <platform>
        <id>181</id>
        <location>
            <point>
                <pos>36.308,24.308,5.0</pos>
            </point>
        </location>
        <description>MicaZ node with Mica Sensor Board.</description>
        <sensor>
            <id>1</id>
            <location>
                <point>
                    <pos>36.308,24.308,5.0</pos>
                </point>
            </location>
            <description>PhotoSensor</description>
            <function name="getCurrentValue">
                <description>This is the first test field</description>
            </function>
            <function name="getAverageValue">
                <description>This is the first test field</description>
                <parameter name="numberElements">
                    <description>This is the first test field</description>
                    <value>1</value>
                </parameter>
            </function>
            <function name="setSampleInterval">
                <description>This is the first test field</description>
                <parameter name="frequency">
                    <description>This is the first test field</description>
                    <value>2</value>
                </parameter>
            </function>
            <type>Light</type>
        </sensor>
    </platform>
</field>
</system>

 <system>
 <id>http://www.google.com</id>
   <field>
    <id>1</id>
    <location>
        <point>
            <pos>36.0,24.0,0.0</pos>
        </point>
    </location>
    <description>This is the first test field</description>
    <function name="minus">
        <description>This is the first test field</description>
        <parameter name="firstVal">
            <description>This is the first test field</description>
            <value>7</value>
        </parameter>
        <parameter name="secondVal">
            <description>This is the first test field</description>
            <value>9</value>
        </parameter>
    </function>
    <platform>
        <id>1</id>
        <location>
            <point>
                <pos>36.0,24.0,0.0</pos>
            </point>
        </location>
        <description>Test Platform MicaSchmidi</description>
        <function name="sub">
            <description>This is the first test field</description>
            <parameter name="firstVal">
                <description>This is the first test field</description>
                <value>1</value>
            </parameter>
        </function>
        <function name="min">
            <description>This is the first test field</description>
            <parameter name="firstVal">
                <description>This is the first test field</description>
                <value>1</value>
            </parameter>
        </function>
        <sensor>
            <id>1</id>
            <location>
                <point>
                    <pos>36.0,24.0,0.0</pos>
                </point>
            </location>
            <description>Put link to datasheet here.</description>
            <function name="mean">
                <description>This is the first test field</description>
            </function>
            <type>Temperature</type>
        </sensor>
    </platform>
</field>
</system>
</query>
